name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: alinazeeshan
          outputs: |
            dist/github-snake.svg?color_snake=#B983FF&color_dots=#161B22,#2E1A47,#4C2673,#6A2C91,#B983FF
            dist/github-snake-dark.svg?color_snake=#B983FF&color_dots=#161B22,#2E1A47,#4C2673,#6A2C91,#B983FF

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
